language: nix

addons:
  ssh_known_hosts: garbas.si

env:
- PKGS_SET=flask
- PKGS_SET=homeassistant

script:
- make pypi2nix $PKGS_SET;
- mkdir nars/;
- nix-push --dest "$PWD/nars/" --force ./result-$PKGS_SET;

before_install:
- git branch
- echo $TRAVIS_BRANCH
- echo 'binary-caches = https://cache.nixos.org/ https://travis.garbas.si/nixpkgs-python/' | sudo tee -a /etc/nix/nix.conf > /dev/null
- openssl aes-256-cbc -K $encrypted_1ae048d151c2_key -iv $encrypted_1ae048d151c2_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy_rsa

after_success:
- rsync -avh --ignore-existing $TRAVIS_BUILD_DIR/nars/ travis@garbas.si:/var/travis/nixpkgs-python/
- if [[ -n `git diff --exit-code` ]]; then
    git config user.name 'travis';
    git config user.email 'travis@garbas.si';
    git status;
    git --no-pager diff $PKGS_SET;
    git stash;
    git checkout -b result-$TRAVIS_BRANCH origin/$TRAVIS_BRANCH;
    git pull;
    git stash apply;
    git add $PKGS_SET;
    git commit -m "Travis update for $PKGS_SET [skip ci]";
    git push git@github.com:garbas/nixpkgs-python.git HEAD:$TRAVIS_BRANCH;
  fi
