branches:
  only:
    - master

language: nix

os:
  - linux
  # - osx

env:
- PKGS_SET=attrs
- PKGS_SET=ckan
- PKGS_SET=django
- PKGS_SET=flake8
- PKGS_SET=flask
- PKGS_SET=homeassistant
- PKGS_SET=pelican
- PKGS_SET=pykube
- PKGS_SET=pypi2nix
- PKGS_SET=pypiserver
- PKGS_SET=pyramid
- PKGS_SET=pytest
- PKGS_SET=science
- PKGS_SET=httpie

script:
- travis_wait 60 make pypi2nix-bin $PKGS_SET;
- mkdir nars/;
- nix copy --to file://./nars/ ./result-pypi2nix-bin
- nix copy --to file://./nars/ ./result-$PKGS_SET;

before_install:
- git branch
- echo $TRAVIS_BRANCH
- sudo mkdir -p /etc/nix
- echo 'binary-caches = https://cache.nixos.org/ https://travis.garbas.si/nixpkgs-python/' | sudo tee -a /etc/nix/nix.conf > /dev/null
- echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
- openssl aes-256-cbc -K $encrypted_1ae048d151c2_key -iv $encrypted_1ae048d151c2_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy_rsa

install:
  - echo 'garbas.si ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPNIqf3Qgnwr/CMslsEK7qIFHOcWWdxvzJIZwBQPjulZ' >> $HOME/.ssh/known_hosts

after_success:
- rsync -avh --ignore-existing /tmp/pypi2nix/cache/wheel/*.whl travis@garbas.si:/var/travis/wheels_cache/
- rsync -avh --ignore-existing $TRAVIS_BUILD_DIR/nars/ travis@garbas.si:/var/travis/nixpkgs-python/
- if [[ -n `git diff --exit-code` ]]; then
    git config user.name 'travis';
    git config user.email 'travis@garbas.si';
    git status;
    git --no-pager diff $PKGS_SET;
    git stash;
    git checkout -b result-$TRAVIS_BRANCH origin/$TRAVIS_BRANCH;
    git pull;
    git stash apply;
    git add $PKGS_SET;
    git commit -m "Travis update for $PKGS_SET [ci skip]";
    git push git@github.com:garbas/nixpkgs-python.git HEAD:$TRAVIS_BRANCH;
  fi
